[package]
edition = "2021"
name = "kuboble-core"
version = "0.1.0"

[dependencies]
arrayvec = {version = "0.7.6", default-features = false}
const_for = "0.1.4"
itertools = {version = "0.13.0", default-features = false}
serde = {version = "1.0.209", default-features = false, features = ["derive"]}
strum = {version = "0.26.3", default-features = false, features = ["derive"]}

[features]
std = []
