[package]
edition = "2021"
name = "pygamer-engine"
version = "0.1.0"

[dependencies]
arrayvec = "0.7.6"
embedded-graphics = "0.7"
embedded-graphics-core = "0.3"
embedded-graphics-framebuf = "0.2"
kuboble-core = {path = "../kuboble-core"}
