[package]
edition = "2021"
name = "kuboble-pc"
version = "0.1.0"

[dependencies]
derive-new = "0.6"
easycurses = "0.13"
#kuboble-core = {path = "../kuboble-core", features = ["std"]}
kuboble-core = {path = "../kuboble-core"}
